### ISSUE TITLE
L3 datamodel is needed to store the reference frame (stacked image) data

### ISSUE THREAD

**Issue by lznakano** [spacetelescope/rad#274]
@nden 

We would like to store the stacked image to an ASDF file.  We need the following:

Meta data
- wcs object:  it  contains similar info as the FITS header
- an image.list file: a text file
- configuration information
- instrument information

Data:
- flux data:   two dimensional float array
- uncertainty data: two dimensional float array
- mask data:  two dimensional short integer array
- coverage:  two dimensional integer array

Question about data type: 
 Is there a C equivalent double precision available? What is the differences between using float vs double in ASDF?

**Comment by braingram** [comment]
Arrays in ASDF support a number of datatypes:
https://asdf-standard.readthedocs.io/en/1.0.3/generated/stsci.edu/asdf/core/ndarray-1.0.0.html#Internal%20Definitions

`double` is likely most similar to `float64`.

**Comment by lznakano** [comment]
Thanks for your quick reply!

**Comment by WilliamJamieson** [comment]
> Is there a C equivalent double precision available? What is the differences between using float vs double in ASDF?

The datatype names are largely C++ derived, eg `double` is `float64` because it is represented by 64 bits.

You will also need to specify the type of integers you are storing, for example `uint32` is an unsigned 32 bit integer while `int32` is a 32 bit signed integer.

From what you describe:
```yaml
%YAML 1.1
---
$schema: asdf://stsci.edu/datamodels/roman/schemas/rad_schema-1.0.0
id: asdf://stsci.edu/datamodels/roman/schemas/<name-of-schema>-1.0.0

title: |
  Title for the schema

type: object
properties:
  meta:
    allOf:
      - $ref: common-1.0.0
      - image_list:
          type: string
  data:
    title: Flux data
    value:
      tag: tag:stsci.edu:asdf/core/ndarray-1.0.0
      datatype: float64
      ndim: 2
  uncertainty:
    title: uncertainty data
    value:
      tag: tag:stsci.edu:asdf/core/ndarray-1.0.0
      datatype: float64
      ndim: 2
  mask:
    title: mask data
    value:
      tag: tag:stsci.edu:asdf/core/ndarray-1.0.0
      datatype: uint32
      ndim: 2
  coverage:
    title: coverage data
    value:
      tag: tag:stsci.edu:asdf/core/ndarray-1.0.0
      datatype: uint32
      ndim: 2
propertyOrder: [meta, data, uncertainty, mask, coverage]
flowStyle: block
required: [meta, data, uncertainty, mask, coverage]
...
```

Should describe your data model. Note that `common` contains all the normal configuration information, see https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/common-1.0.0.yaml and https://github.com/spacetelescope/rad/blob/main/src/rad/resources/schemas/basic-1.0.0.yaml

Note that, I guessed at the names for the keywords (`image_list, `data`, `uncertainty`, `mask`, `coverage`) and the integer datatypes. 

Finally, please let me know what exactly you want to call these things, and specify exactly what you want your datamodel to be called, and provide a short description of it.
