### ISSUE TITLE
Docs: Clarification that file schema means top-level field's tag schemas

### ISSUE THREAD

**Issue by ketozhang** [spacetelescope/rad#427]
In the docs there's a handful of mentions of "file schema" which are separately listed than the "tags". For those unfamiliar with ASDF, this isn't particularly harmful. For those more familiar with ASDF, it's a bit ambiguous because file schema can also mean a schema to describe the file schema as a whole.

Discussing with @braingram , I come to learn that ...

> the "file schema" headings there refer to the ASDF schema used for the top-level roman object in the file.
> — @braingram

..., therefore all file schemas are actually tag schemas and only validates the fields under `roman` rather than a schema for the entire file. 

```yaml
...
roman: !<asdf://path/to/schemas/schema-x.y.z>
  meta: ...
  data: ...
```

Furthermore, there isn't a true file schema that enforces `roman` must be used as the top level. Perhaps something with this schema...

```yaml
allOf:
  - $ref: http://stsci.edu/schemas/asdf/asdf-schema-1.0.0
  - type: object
    properties:
      roman:
        type: object
    required: [roman]
```
