### ISSUE TITLE
Add MA table reference file

### ISSUE THREAD

**Issue by tddesjardins** [spacetelescope/rad#461]
To better keep in sync the versions of the multi-accumulation (MA) tables used by various simulation tools at the SOC as well as by the romancal pipeline, we request a new type of reference file to capture this information. I welcome comments on this issue for how best to format the file, but I'm going to sketch out an initial suggestion here. Note that ref_common includes ROMAN.META.INSTRUMENT.DETECTOR, but this would apply to all detectors...I guess we can just always put WFI01? We're not going to match on it, so we don't need to put a p_ keyword for this, just a placeholder.

CRDS Selectors:
- ROMAN.META.EXPOSURE.START_TIME

Schema:
```
title: WFI Multi-Accumulation (MA) Tables

type: object
properties:
     meta:
          allOf:
               - $ref_common
               - type: object
                     properties:
                          type: string
                         enum: [MATAB]
     ma_table:
          title: Multi-Accumulation (MA) Table Readout Patterns
          description: Readout specifications of the multi-accumulation (MA) tables.
          type: object
          patternProperties:
               ??? - Need to put the MA table ID numbers here...can we leave this general to any integer 1 – 99?
               type: object
               properties:
                    read_pattern:
                         title: Readout Pattern
                         description: The enumeration of detector reads to resultants making up the Level 1 ramp data cube. The read pattern is nested such that each grouping of read numbers represents a resultant. For example, a readout pattern of [[1], [2, 3], [4]] consists of four reads that were downlinked as three resultants with both the first and last resultant each containing a single read.
                         type: array
                         items:
                             type: array
                             items:
                                 type: integer
     timing:
          title: Detector Readout Time (s)
         description: The readout time per observing mode in seconds of the Wide Field Instrument (WFI) detectors. This represents the time between the start and end of the readout. The difference in readout times is governed by the guide window mode in use, which is tied to the observing mode.
         patternProperties: 
                "^(WFI_IMAGE|WFI_GRISM|WFI_PRISM|WFI_WFSC)$":
                       frame_time:
                            title: Detector Readout Time (s)
                            description: The readout time in seconds of the Wide Field Instrument (WFI) detectors. This represents the time between the start and end of the readout.
```

Questions:
1. What does exposure type WFI_WFSC represent? There are differences in the frame times between WFI imaging, WFI spectroscopy, large defocus, and moderate defocus modes. Expect these to change, but in last PRD this was 3.04, 4.03, 4.41, and 6.40 seconds, respectively). Does WFI_WFSC correspond to one of the defocus modes? Both? We may need to think about this...
