### ISSUE TITLE
flat schema specifies a float32 dq array

### ISSUE THREAD

**Issue by eslavich** [spacetelescope/rad#8]
In rad, the schema defines dq like this:
```
dq: 
  tag: tag:stsci.edu:asdf/core/ndarray-1.0.0 
  datatype: float32
  ndim: 2
```

but in romancal:
```
dq:
  title: Data quality array
  default: 0
  datatype: uint16
```
